pull_request_rules:
  - name: automatic merge for master when reviewed and CI passes
    conditions:
      - check-success=Run E2E Backend + Frontend Tests
      - check-success=Build in production mode
      - check-success=Lint Heimdall
      - check-success=Run Backend Tests
      - check-success=Run Frontend Tests
      - check-success=security/snyk (rbclark)
      - check-success=netlify/heimdall-lite/deploy-preview
      - "check-success=LGTM analysis: JavaScript"
      - check-success=SonarCloud Code Analysis
      - "#approved-reviews-by>=1"
      - base=master
      - label=ready-to-merge
    actions:
    actions:
        merge:
          strict: true
          method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request has conflict. Could you fix it @{{author}}?
