name: Run E2E Backend + Frontend Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
     - uses: actions/checkout@v2

     - name: Cache node modules
       uses: actions/cache@v2
       env:
         cache-name: cache-node-modules
       with:
         # npm cache files are stored in `~/.npm` on Linux/macOS
         path: ~/.npm
         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
           ${{ runner.os }}-build-${{ env.cache-name }}-
           ${{ runner.os }}-build-
           ${{ runner.os }}-

     - name: Setup Node.js
       uses: actions/setup-node@v1
       with:
        node-version: '14.x'

     - name: Install project dependencies
       run: yarn install --frozen-lockfile

     - name: Copy .env-ci to .env
       run: cp apps/backend/test/.env-ci apps/backend/.env

     - name: Create/migrate db
       run: |
        yarn backend sequelize-cli db:create
        yarn backend sequelize-cli db:migrate

     - name: Build frontend and server for E2E UI tests
       run: yarn run build

     - name: Run e2e UI tests
       run: yarn backend test:ui
