name: Run E2E Backend + Frontend Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CYPRESS_TESTING: true
      NODE_ENV: test
      LDAP_ENABLED: true
      LDAP_HOST: ldap
      LDAP_PORT: 10389
      LDAP_BINDDN: cn=admin,dc=planetexpress,dc=com
      LDAP_PASSWORD: GoodNewsEveryone
      LDAP_SEARCHBASE: ou=people,dc=planetexpress,dc=com
      LDAP_SEARCHFILTER: (uid={{username}})
      LDAP_NAMEFIELD: cn
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      ldap:
        image: rroemhild/test-openldap
        ports:
          - 10389:10389

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Copy .env-ci to .env
        run: cp apps/backend/test/.env-ci apps/backend/.env

      - name: Create/migrate db
        run: |
          yarn backend sequelize-cli db:create
          yarn backend sequelize-cli db:migrate
          yarn backend sequelize-cli db:seed:all

      - name: Build Heimdall
        run: yarn build
        env:
          NODE_ENV: production

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: http://127.0.0.1:3000

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: cypress-screenshots
          path: test/screenshots

networks:
  heimdallci:
