name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
     DATABASE_HOST: localhost
     DATABASE_PORT: 5432
     DATABASE_USERNAME: postgres
     DATABASE_PASSWORD: postgres
     DATABASE_NAME: heimdallts_jest_testing_service_db
     JWT_SECRET: test
     NODE_ENV: production

    steps:
     - uses: actions/checkout@v2
     - name: Setup Node.js
       uses: actions/setup-node@v1
       with:
        node-version: '12.x'
     - name: Setup PostgresSQL database
       uses: harmon758/postgresql-action@v1
       with:
        postgresql db: heimdallts_jest_testing_service_db
        postgresql user: postgres
        postgresql password: postgres

     - name: Install dependencies
       run: npm ci

     - name: Run unit tests
       run: |
         npx sequelize-cli db:migrate
         npm run test
     - name: Run e2e tests
       run: npm run test:e2e

     - name: Run test coverage
       run: npm run test:cov

     - name: Run lint
       run: npm run lint
