name: Test

on:
  push:
    branches: [ ss-testing-pipeline ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
     - uses: actions/checkout@v2
     - name: Setup Node.js
       uses: actions/setup-node@v1
       with:
        node-version: '12.x'
     - name: Setup PostgresSQL database
       uses: harmon758/postgresql-action@v1
       with:
        postgresql db: heimdallts_jest_testing_service_db
        postgresql user: postgres
        postgresql password: postgres

     - name: Install dependencies
       run: npm ci

     - name: Run lint
       run: npm run lint

     - name: Copy .env-ci to .env
       run: cp test/.env-ci .env

     - name: Create/migrate db
       run: |
         npx sequelize-cli db:migrate

     - name: Run test coverage
       run: npm run test:cov

